### ISSUE TITLE
Could you compile the 'vignette in R Notebook format'?

### ISSUE THREAD

**Issue by pbrazda** [QinglinMei/RCSL#2]
Hi, 
Could you compile the 'vignette in R Notebook format'? Right now it is not available under [the link](https://github.com/QinglinMei/RCSL/blob/master/vignettes/RCSL-vignette.Rmd). I guess it would be and html report.

Thank you!!

**Comment by QinglinMei** [comment]
Hi,
I hope this email finds you well. I' sorry for the delayed response. Upon reviewing the issue, I discovered a mistake in the path, which has now been rectified. Additionally, I wanted to inform you that the vignette can be built by setting build_vignettes = TRUE when installing the package[devtools::install_github("QinglinMei/RCSL",build_vignettes = T)]

Thank you for your reminder!
